name: Node.js CI

on:
  push:
    branches:
      - main
    tags: 
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      node-version: 16.x # See Node.js release schedule: https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build with Node v${{ env.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - run: yarn run build

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: main

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
        artifacts: extension/chrome.zip, extension/edge.zip, extension/opera.zip, extension/firefox.xpi
